### ISSUE TITLE
Add Project is not clickable when the user has no project

### ISSUE THREAD

**Issue by awijasa** [upstreamplugin/UpStream-Frontend-Edit#121]
Assuming this is fixed: https://github.com/upstreamplugin/UpStream/issues/699, Add Project button at the /projects (frontend) would still be unclickable.

**Comment by andergmartins** [comment]
Fixed on the referenced Pull Request.

**Comment by oraclerob** [comment]
This is still not fixed - project is always 0 when on this page (as you have no open project). I'm going to put a fix in which selects the first or last project to copy.

**Comment by andergmartins** [comment]
Hi @oraclerob thanks. Agreed. That was closed by mistake. We will take another look.

**Comment by oraclerob** [comment]
I've fixed this already and this will be pushed up with pull request for #132.
